version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: './PHPDOCKER'
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html/api'
    depends_on:
      - mysql
    links:
      - mysql
    dns: '8.8.8.8'
    environment:
#    remote_connect_back instead of remote_host is nicer
      XDEBUG_CONFIG: "idekey=jetdebug remote_enable=On remote_connect_back=1"
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '.'
    ports:
      - '3306:3306'