version: 3

drawgame:
  server:
    image: php:7.2.3-apache-stretch
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/api
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "."
    ports:
      - "3306:3306"
